version: '3.9'

services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5432}:5432
    environment:
      POSTGRES_DB: autodeal
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql
    restart: always
